import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faFolder,
    faTimes,
    faTrash,
    faEnvelope,
    faSearch,
    faBatteryThreeQuarters,
    faPowerOff,
    faVolumeUp,
    faWifi,
    faPaperPlane,
    faCog,
    faChevronRight,
    faChevronDown,
    faRocket,
    faUserCircle,
    faGraduationCap,
    faWrench,
    faBriefcase,
    faLightbulb,
    faCommentAlt,
    faFilePdf,
    faFileWord,
    faArrowLeft,
    faArrowRight
} from "@fortawesome/free-solid-svg-icons";
import {
    faWindowMinimize,
    faWindowMaximize,
    faWindowRestore,
} from "@fortawesome/free-regular-svg-icons";
import {
    faLinkedinIn,
    faGithub,
    faDiscord
} from "@fortawesome/free-brands-svg-icons";

library.add(
    faFolder,
    faTimes,
    faTrash,
    faEnvelope,
    faSearch,
    faBatteryThreeQuarters,
    faPowerOff,
    faVolumeUp,
    faWifi,
    faPaperPlane,
    faCog,
    faChevronRight,
    faChevronDown,
    faRocket,
    faUserCircle,
    faGraduationCap,
    faWrench,
    faBriefcase,
    faLightbulb,
    faCommentAlt,
    faFilePdf,
    faFileWord,
    faArrowLeft,
    faArrowRight,
    faWindowMinimize,
    faWindowMaximize,
    faWindowRestore,
    faLinkedinIn,
    faGithub,
    faDiscord
);
